-- Empresa
create table if not exists elofy_company (
  id         uuid primary key default gen_random_uuid(),
  elofy_id   text unique not null,
  nome       text,
  id_grupo_economico text,
  raw_data   jsonb,
  synced_at  timestamptz default now()
);

-- Times
create table if not exists elofy_teams (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  nome                  text,
  status                text,
  codigo_origem         text,
  id_responsavel        text,
  nome_responsavel      text,
  id_time_pai           text,
  nome_time_pai         text,
  ids_tags              text,
  tags                  text,
  id_empresa            text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Cargos
create table if not exists elofy_positions (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  cargo                 text,
  status                text,
  codigo_origem         text,
  descricao             text,
  dificuldade           text,
  impacto               text,
  mapeado_sucessao      text,
  regua                 text,
  id_empresa            text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Usuários / Colaboradores
create table if not exists elofy_users (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  nome                  text,
  matricula             text,
  status                text,
  data_admissao         text,
  data_desligamento     text,
  id_gestor             text,
  nome_gestor           text,
  email                 text,
  login                 text,
  tipo_cargo            text,
  id_cargo              text,
  cargo                 text,
  nivel_responsabilidade text,
  id_time               text,
  nome_time             text,
  ids_times_acessiveis  text,
  times_acessiveis      text,
  projeto_pod           text,
  ids_perfil            text,
  perfis                text,
  cpf                   text,
  colaborador_chave     text,
  id_empresa            text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);
-- Competências
create table if not exists elofy_competencies (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  competencia           text,
  categoria             text,
  descricao             text,
  ids_times             text,
  nomes_times           text,
  ids_cargos            text,
  nomes_cargos          text,
  esperado              text,
  o_que_queremos        text,
  o_que_nao_queremos    text,
  comportamentos        text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Configurações de revisão de ciclo
create table if not exists elofy_cycle_review_config (
  id                              uuid primary key default gen_random_uuid(),
  elofy_id                        text unique not null,
  id_empresa                      text,
  nome_empresa                    text,
  id_revisao                      text,
  nome_ciclo                      text,
  id_ciclo                        text,
  nome_revisao                    text,
  status_revisao                  text,
  liberacao_notas                 text,
  calibracao_notas                text,
  responder_avaliacoes            text,
  ano                             text,
  janela                          text,
  trimestre_inicio                text,
  trimestre_fim                   text,
  data_inicio_ciclo               text,
  data_fim_ciclo                  text,
  dias_faltando                   text,
  regua                           text,
  data_corte_elegibilidade        text,
  tipo_publico                    text,
  etapa                           text,
  nome_etapa                      text,
  autoavaliacao                   text,
  pares                           text,
  clientes_internos               text,
  gestor                          text,
  equipe                          text,
  permitir_comentarios            text,
  comentarios_obrigatorios        text,
  gestores_avaliados              text,
  selecao_pares_rh                text,
  visualizacao_rapida_objetivos   text,
  avaliar_okr                     text,
  avaliar_responsaveis_kr         text,
  avaliar_responsaveis_corresps   text,
  nao_avaliar_kr_estrategicos     text,
  avaliacao_por_entregas          text,
  avaliacao_responsaveis_init     text,
  raw_data                        jsonb,
  synced_at                       timestamptz default now()
);
-- Avaliação detalhada (nível raiz)
create table if not exists elofy_cycle_review_detailed (
  id                          uuid primary key default gen_random_uuid(),
  elofy_id                    text unique not null,
  id_revisao_ciclo            text,
  ano                         integer,
  nome_ciclo                  text,
  id_empresa                  text,
  id_revisao_ciclos_avaliacoes text,
  id_avaliado                 text,
  matricula_avaliado          text,
  nome_avaliado               text,
  id_time_avaliado            text,
  nome_time_avaliado          text,
  tipo_cargo_avaliado         text,
  id_tipo_cargo_avaliado      text,
  id_cargo_avaliado           text,
  cargo_avaliado              text,
  id_gestor_avaliado          text,
  gestor_avaliado             text,
  media_final_avaliacao       text,
  label_nbox                  text,
  quadrante_nbox              text,
  tipo_avaliacao              text,
  id_avaliador                text,
  matricula_avaliador         text,
  avaliador                   text,
  id_time_avaliador           text,
  nome_time_avaliador         text,
  tipo_cargo_avaliador        text,
  id_cargo_avaliador          text,
  cargo_avaliador             text,
  raw_data                    jsonb,
  synced_at                   timestamptz default now()
);

-- Etapas da avaliação detalhada
create table if not exists elofy_cycle_review_steps (
  id                          uuid primary key default gen_random_uuid(),
  elofy_id                    text unique not null,
  cycle_review_detailed_id    text not null,
  etapa                       text,
  media_fase                  numeric,
  nome_etapa                  text,
  conceito_media_etapa        text,
  comentario_unico_fase       text,
  id_revisao_ciclo_fases      text,
  raw_data                    jsonb,
  synced_at                   timestamptz default now()
);

-- Itens avaliados dentro das etapas
create table if not exists elofy_cycle_review_items (
  id                                  uuid primary key default gen_random_uuid(),
  elofy_id                            text unique not null,
  step_id                             text not null,
  nota                                numeric,
  conceito                            text,
  comentario                          text,
  item_avaliado                       text,
  id_revisao_ciclo_avaliacoes_fase    text,
  raw_data                            jsonb,
  synced_at                           timestamptz default now()
);

-- Revisão de ciclo público (scores por colaborador)
create table if not exists elofy_cycle_review_public (
  id                          uuid primary key default gen_random_uuid(),
  elofy_id                    text unique not null,
  id_empresa                  text,
  id_revisao_score            text,
  id_revisao_ciclo            text,
  nome_revisao                text,
  id_usuario_avaliado         text,
  matricula_avaliado          text,
  nome_avaliado               text,
  status_avaliado             text,
  media_final                 text,
  fase                        text,
  media_fase                  text,
  media_fase_auto             text,
  media_fase_gestor           text,
  media_fase_pares            text,
  media_fase_equipe           text,
  media_fase_cliente          text,
  raw_data                    jsonb,
  synced_at                   timestamptz default now()
);

-- Notas por fase (Carreira)
create table if not exists elofy_cycle_review_note_step (
  id                              uuid primary key default gen_random_uuid(),
  elofy_id                        text unique not null,
  id_empresa                      text,
  id_revisao_score                text,
  id_revisao_ciclo                text,
  nome_revisao                    text,
  id_usuario_avaliado             text,
  nome_usuario                    text,
  status_avaliado                 text,
  id_gestor                       text,
  nome_gestor                     text,
  media_final_ciclo               text,
  conceito_final_ciclo            text,
  conceito_final_ciclo_calibrado  text,
  nine_box                        text,
  quadrante_nbox                  text,
  quadrante_nbox_calibrado        text,
  media_fase_competencia          text,
  conceito_fase_competencia       text,
  media_competencia_auto          text,
  conceito_competencia_auto       text,
  media_competencia_gestor        text,
  conceito_competencia_gestor     text,
  media_competencia_pares         text,
  conceito_competencia_par        text,
  media_competencia_time          text,
  conceito_competencia_time       text,
  media_competencias_clientes     text,
  conceito_competencia_clientes   text,
  media_resultados                text,
  conceito_resultados             text,
  media_resultados_auto           text,
  conceito_resultados_auto        text,
  media_resultados_gestor         text,
  conceito_resultados_gestor      text,
  media_resultados_pares          text,
  conceito_resultados_pares       text,
  media_resultados_time           text,
  conceito_resultados_time        text,
  media_resultados_clientes       text,
  conceito_resultados_clientes    text,
  media_valores                   text,
  conceito_valores                text,
  media_valores_auto              text,
  conceito_valores_auto           text,
  media_valores_gestor            text,
  conceito_valores_gestor         text,
  media_valores_pares             text,
  conceito_valores_pares          text,
  media_valores_time              text,
  conceito_valores_time           text,
  media_valores_clientes          text,
  conceito_valores_clientes       text,
  raw_data                        jsonb,
  synced_at                       timestamptz default now()
);

-- Médias fase competências
create table if not exists elofy_cycle_review_avg_competencies (
  id                              uuid primary key default gen_random_uuid(),
  elofy_id                        text unique not null,
  id_empresa                      text,
  id_revisao_score                text,
  id_revisao_ciclo                text,
  nome_revisao                    text,
  periodo                         text,
  id_usuario_avaliado             text,
  nome_usuario_avaliado           text,
  id_gestor                       text,
  nome_gestor                     text,
  conceito_final_ciclo            text,
  media_final_ciclo_calibrado     text,
  conceito_final_ciclo_calibrado  text,
  media_competencia               text,
  media_competencia_auto          text,
  media_competencia_gestor        text,
  media_competencia_pares         text,
  media_competencia_equipe        text,
  media_competencia_clientes      text,
  raw_data                        jsonb,
  synced_at                       timestamptz default now()
);

-- Médias fase resultados
create table if not exists elofy_cycle_review_avg_results (
  id                              uuid primary key default gen_random_uuid(),
  elofy_id                        text unique not null,
  id_empresa                      text,
  id_revisao_avaliacoes_fase      text,
  id_revisao_ciclo                text,
  nome_revisao                    text,
  id_usuario_avaliado             text,
  nome_usuario_avaliado           text,
  id_gestor                       text,
  nome_gestor                     text,
  conceito_final_ciclo            text,
  media_final_ciclo_calibrado     text,
  conceito_final_ciclo_calibrado  text,
  media_final_fase_resultados     text,
  item_avaliado                   text,
  media_item_avaliado             text,
  media_item_auto                 text,
  media_item_gestor               text,
  media_item_pares                text,
  media_item_equipe               text,
  media_item_clientes             text,
  media_final                     text,
  raw_data                        jsonb,
  synced_at                       timestamptz default now()
);

-- Ninebox
create table if not exists elofy_cycle_review_ninebox (
  id                              uuid primary key default gen_random_uuid(),
  elofy_id                        text unique not null,
  id_empresa                      text,
  id_revisao_score                text,
  id_revisao_ciclo                text,
  periodo                         text,
  nome_revisao                    text,
  data_inicio                     timestamptz,
  data_fim                        timestamptz,
  id_usuario_avaliado             text,
  nome_usuario_avaliado           text,
  status_avaliado                 text,
  id_gestor                       text,
  nome_gestor                     text,
  media_final_ciclo               text,
  conceito_final_ciclo            text,
  conceito_final_ciclo_calibrado  text,
  fase_eixo_x                     text,
  nota_eixo_x                     text,
  fase_eixo_y                     text,
  nota_eixo_y                     text,
  quadrante_nbox                  text,
  quadrante_nbox_calibrado        text,
  pessoa_chave                    text,
  talento                         text,
  singular                        text,
  reconhecimento                  text,
  raw_data                        jsonb,
  synced_at                       timestamptz default now()
);
-- Períodos
create table if not exists elofy_periods (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  periodo               text,
  data_inicio           text,
  data_fim              text,
  situacao              text,
  escala_peso_obj       text,
  nome_padrao_objetivo  text,
  escala_peso_kr        text,
  periodicidade_kr      text,
  modulo                text,
  id_empresa            text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Períodos detalhados
create table if not exists elofy_periods_detailed (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  periodo                   text,
  data_inicial              date,
  data_final                date,
  escala_pesos_kr           text,
  escala_pesos_meta         text,
  possui_ciclo_competencias text,
  ciclos_com_competencias   text,
  amplitude_competencia     text,
  possui_ciclo_potencial    text,
  ciclos_com_potencial      text,
  amplitude_potencial       text,
  possui_ciclo_valores      text,
  ciclos_com_valores        text,
  amplitude_valores         text,
  possui_ciclo_resultados   text,
  ciclos_com_resultados     text,
  amplitude_resultados      text,
  possui_ciclo_feedback     text,
  ciclos_com_feedback       text,
  amplitude_feedback        text,
  possui_ciclos_nota_final  text,
  ciclos_nota_final         text,
  possui_ppr                text,
  possui_rv                 text,
  possui_calibragem         text,
  ciclos_com_calibragem     text,
  possui_nbox               text,
  ciclos_nbox               text,
  possui_pdi                text,
  possui_sucessao           text,
  possui_feedback           text,
  possui_one_one            text,
  quantidade_pdis           integer,
  quantidade_feedback       integer,
  quantidade_one_one        integer,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Ciclos
create table if not exists elofy_cycles (
  id          uuid primary key default gen_random_uuid(),
  elofy_id    text unique not null,
  ciclo       text,
  id_periodo  text,
  data_inicio text,
  data_fim    text,
  situacao    text,
  status      text,
  id_empresa  text,
  raw_data    jsonb,
  synced_at   timestamptz default now()
);

-- Direcionadores
create table if not exists elofy_drivers (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  id_periodo                text,
  nome_periodo              text,
  nome_direcionador         text,
  progresso                 text,
  descricao                 text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  matricula_gestor          text,
  status                    text,
  atrela_metas              text,
  tipo_direcionador         text,
  corresponsaveis           jsonb,
  tags                      jsonb,
  itens_vinculados          jsonb,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Objetivos
create table if not exists elofy_objectives (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  id_periodo                text,
  periodo                   text,
  id_ciclo                  text,
  ciclo                     text,
  id_direcionador           text,
  direcionador              text,
  id_objetivo_pai           text,
  objetivo_pai              text,
  objetivo                  text,
  objetivo_estrategico      text,
  descricao                 text,
  tipo                      text,
  id_responsavel            text,
  responsavel               text,
  id_corresponsavel         text,
  corresponsavel            text,
  time                      text,
  workflow                  text,
  tags                      text,
  peso                      text,
  progresso                 text,
  sentimento                text,
  status                    text,
  ativo                     text,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Resultados chave (Key Results)
create table if not exists elofy_key_results (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_objetivo           text,
  resultado_chave       text,
  descricao             text,
  workflow              text,
  id_responsavel        text,
  responsavel           text,
  id_corresponsavel     text,
  corresponsavel        text,
  peso                  text,
  unidade_medida        text,
  meta                  text,
  ponto_partida         text,
  direcao               text,
  manutencao            text,
  medicao_atual         text,
  data_medicao_atual    text,
  progresso             text,
  periodicidade         text,
  checkins_pendentes    text,
  sentimento            text,
  status                text,
  tipo_informacao       text,
  tipo_score            text,
  formula_calculo       text,
  tags                  text,
  modulo                text,
  ativo                 text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- OKRs V2
create table if not exists elofy_okrs_v2 (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  nome_objetivo             text,
  ativo                     text,
  workflow                  text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  matricula_gestor          text,
  peso                      text,
  progresso                 text,
  id_periodo                text,
  periodo                   text,
  periodo_ciclos            jsonb,
  corresponsaveis           jsonb,
  resultados_chave          jsonb,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Contrato de metas V2
create table if not exists elofy_goals_contract_v2 (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  nome_objetivo             text,
  ativo                     text,
  workflow                  text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  matricula_gestor          text,
  peso                      text,
  progresso                 text,
  id_periodo                text,
  periodo                   text,
  periodo_ciclos            jsonb,
  metas                     jsonb,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Base de indicadores
create table if not exists elofy_base_indicators (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_empresa            text,
  nome_empresa          text,
  nome_indicador        text,
  descricao             text,
  ativo                 text,
  dimensao              text,
  origem                text,
  peso                  text,
  tipo_informacao       text,
  forma_calculo         text,
  tipo_score            text,
  id_periodo            text,
  nome_periodo          text,
  casas_decimais        integer,
  ponto_partida         text,
  periodicidade         text,
  manutencao            text,
  meta                  text,
  score                 text,
  minimo                text,
  maximo                text,
  maximo2               text,
  meta_jan              text,
  checkin_jan           text,
  meta_fev              text,
  checkin_fev           text,
  meta_mar              text,
  checkin_mar           text,
  meta_abr              text,
  checkin_abr           text,
  meta_maio             text,
  checkin_maio          text,
  meta_jun              text,
  checkin_jun           text,
  meta_jul              text,
  checkin_jul           text,
  meta_ago              text,
  checkin_ago           text,
  meta_set              text,
  checkin_set           text,
  meta_out              text,
  checkin_out           text,
  meta_nov              text,
  checkin_nov           text,
  meta_dez              text,
  checkin_dez           text,
  meta_anual            text,
  checkin_anual         text,
  metas_vinculadas      jsonb,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);
-- PDI
create table if not exists elofy_pdi (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_empresa            text,
  id_responsavel        text,
  matricula             text,
  responsavel           text,
  titulo_pdi            text,
  cargo_responsavel     text,
  time_responsavel      text,
  cargos_vinculados     text,
  competencias_vinculadas text,
  prazo                 text,
  status_pdi            text,
  progresso_pdi         text,
  situacao_pdi          text,
  id_iniciativa         text,
  iniciativa            text,
  tipo_iniciativa       text,
  prazo_iniciativa      text,
  status_iniciativa_label text,
  progresso_iniciativa  text,
  status_iniciativa     text,
  data_conclusao        text,
  data_criacao_iniciativa text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Iniciativas
create table if not exists elofy_initiatives (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  iniciativa                text,
  descricao                 text,
  nro_sub_iniciativas       integer,
  id_iniciativa_pai         text,
  nome_iniciativa_pai       text,
  status_iniciativa         text,
  data_inicio               date,
  data_final                text,
  situacao_iniciativa       text,
  progresso_iniciativa      integer,
  data_conclusao            date,
  disponivel_avaliacao      text,
  origem                    text,
  tags                      text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  corresponsaveis           text,
  id_resultado_chave        text,
  resultado_chave           text,
  progresso_resultado_chave integer,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Iniciativas PDI
create table if not exists elofy_initiatives_pdi (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  iniciativa                text,
  descricao                 text,
  status_iniciativa         text,
  data_inicio               text,
  data_final                text,
  situacao_iniciativa       text,
  data_conclusao            text,
  progresso_iniciativa      integer,
  disponivel_avaliacao      text,
  origem                    text,
  tags                      text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  data_criacao              text,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Iniciativas 1-1
create table if not exists elofy_initiatives_one_one (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  iniciativa                text,
  status_iniciativa         text,
  data_inicio               text,
  data_final                text,
  situacao_iniciativa       text,
  data_conclusao            text,
  progresso_iniciativa      integer,
  disponivel_avaliacao      text,
  origem                    text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);
-- Feedbacks
create table if not exists elofy_feedbacks (
  id                            uuid primary key default gen_random_uuid(),
  elofy_id                      text unique not null,
  id_empresa                    text,
  acao                          text,
  data_feedback                 date,
  prazo_esperado                date,
  id_usuario_remetente          text,
  matricula_remetente           text,
  usuario_remetente             text,
  cargo_remetente               text,
  time_remetente                text,
  id_usuario_destinatario       text,
  matricula_destinatario        text,
  usuario_destinatario          text,
  cargo_destinatario            text,
  time_destinatario             text,
  tipo_feedback                 text,
  solicitacao                   text,
  pergunta                      text,
  resposta                      text,
  valores_competencias          text,
  raw_data                      jsonb,
  synced_at                     timestamptz default now()
);

-- Mural de elogios
create table if not exists elofy_praises_board (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_empresa            text,
  elogio                text,
  data                  date,
  hora                  text,
  id_usuario_remetente  text,
  usuario_remetente     text,
  badge                 text,
  tags                  text,
  id_usuario_elogiado   text,
  usuario_elogiado      text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Termômetro de sentimentos
create table if not exists elofy_feelings (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_empresa            text,
  id_usuario            text,
  usuario               text,
  id_cargo              text,
  cargo                 text,
  id_time               text,
  time                  text,
  id_gestor             text,
  gestor                text,
  id_tipo_sentimento    text,
  tipo_sentimento       text,
  id_motivo             text,
  motivo                text,
  comentario            text,
  data_criacao          text,
  hora_criacao          text,
  categorias_trabalho   jsonb,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);
-- Reuniões 1-1
create table if not exists elofy_one_one (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  template                  text,
  status_one_one            text,
  id_usuario_remetente      text,
  nome_usuario_remetente    text,
  status_remetente          text,
  id_gestor_remetente       text,
  nome_gestor_remetente     text,
  data                      date,
  horario                   text,
  duracao                   integer,
  id_usuario_convidado      text,
  nome_usuario_convidado    text,
  status_convidado          text,
  motivo                    text,
  situacao                  text,
  id_ciclo_avaliacao        text,
  nome_ciclo_avaliacao      text,
  tags                      text,
  compartilhado             jsonb,
  iniciativas               jsonb,
  talking_points            jsonb,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Sucessão
create table if not exists elofy_succession (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_empresa            text,
  nome_empresa          text,
  nome_cargo            text,
  descricao             text,
  dificuldade           text,
  impacto               text,
  situacao_cargo        text,
  classificacao         text,
  requisitos_posicao    text,
  usuarios_atuais       jsonb,
  sucessao              jsonb,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);
-- Pesquisas (relatório geral sem respostas)
create table if not exists elofy_surveys (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_pesquisa             text,
  id_tipo_pesquisa          text,
  tipo_pesquisa             text,
  id_questionario           text,
  questionario              text,
  data_inicio               text,
  data_fim                  text,
  situacao                  text,
  pesquisa_anonima          text,
  numero_pendencias         text,
  numero_respondentes       text,
  adesao                    text,
  status_pesquisa           text,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Pesquisas de desligamento
create table if not exists elofy_survey_dismiss (
  id                          uuid primary key default gen_random_uuid(),
  elofy_id                    text unique not null,
  id_empresa                  text,
  id_pesquisa                 text,
  nome_pesquisa               text,
  id_publico_pesquisa         text,
  id_usuario_desligado        text,
  matricula_usuario_desligado text,
  usuario_desligado           text,
  id_cargo_desligado          text,
  cargo_desligado             text,
  id_time_desligado           text,
  time_desligado              text,
  id_gestor_desligado         text,
  matricula_gestor_desligado  text,
  nome_gestor_desligado       text,
  data_desligamento           text,
  id_tipo_desligamento        text,
  tipo_desligamento           text,
  id_usuario_respondente      text,
  matricula_respondente       text,
  usuario_respondente         text,
  id_cargo_respondente        text,
  nome_cargo_respondente      text,
  id_time_respondente         text,
  time_respondente            text,
  modo_envio_pesquisa         text,
  id_pergunta                 text,
  id_resposta                 text,
  pergunta                    text,
  justificativa               text,
  resposta                    text,
  status_pesquisa             text,
  data_resposta               text,
  id_categoria_pergunta       text,
  nome_categoria_pergunta     text,
  status_pesquisa_ativa       text,
  raw_data                    jsonb,
  synced_at                   timestamptz default now()
);

-- Pesquisas Pulse
create table if not exists elofy_survey_pulse (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_empresa            text,
  id_pesquisa           text,
  nome_pesquisa         text,
  situacao_pesquisa     text,
  data_pulso            text,
  data_resposta         text,
  id_usuario            text,
  usuario               text,
  id_time               text,
  time                  text,
  id_gestor             text,
  gestor                text,
  id_categoria_pergunta text,
  categoria_pergunta    text,
  id_pergunta           text,
  pergunta              text,
  score_resposta        text,
  resposta              text,
  justificativa         text,
  id_resposta           text,
  status_pesquisa       text,
  id_publico_pesquisa   text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Pesquisas Padrão e Enquetes
create table if not exists elofy_survey_standard (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_empresa            text,
  id_pesquisa           text,
  nome_pesquisa         text,
  situacao_pesquisa     text,
  data_envio_pesquisa   text,
  id_usuario            text,
  usuario               text,
  id_cargo              text,
  cargo                 text,
  id_time               text,
  time                  text,
  id_gestor             text,
  nome_gestor           text,
  status_resposta       text,
  data_resposta         text,
  id_categoria_pergunta text,
  categoria_pergunta    text,
  id_tipo_pergunta      text,
  tipo_pergunta         text,
  id_pergunta           text,
  pergunta              text,
  resposta              text,
  justificativa         text,
  status_pesquisa       text,
  id_resposta           text,
  id_publico_pesquisa   text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Pesquisas Temporais
create table if not exists elofy_survey_temporal (
  id                          uuid primary key default gen_random_uuid(),
  elofy_id                    text unique not null,
  id_empresa                  text,
  id_pesquisa                 text,
  nome_pesquisa               text,
  situacao_pesquisa           text,
  data_envio_pesquisa         date,
  id_tipo_respondente         text,
  tipo_respondente            text,
  id_usuario_respondente      text,
  usuario_respondente         text,
  id_cargo_respondente        text,
  cargo_respondente           text,
  id_time_respondente         text,
  time_respondente            text,
  id_usuario_avaliado         text,
  usuario_avaliado            text,
  id_cargo_avaliado           text,
  cargo_avaliado              text,
  id_time_avaliado            text,
  time_avaliado               text,
  data_admissao_avaliado      text,
  status_resposta             text,
  data_resposta               text,
  id_categoria_pergunta       text,
  categoria_pergunta          text,
  id_tipo_pergunta            text,
  tipo_pergunta               text,
  id_pergunta                 text,
  pergunta                    text,
  resposta                    text,
  justificativa               text,
  status_pesquisa             text,
  id_resposta                 text,
  id_publico_pesquisa         text,
  raw_data                    jsonb,
  synced_at                   timestamptz default now()
);
-- Situação de integrações
create table if not exists elofy_integration_situation (
  id                                  uuid primary key default gen_random_uuid(),
  elofy_id                            text unique not null,
  id_lote                             text,
  codigo_movimento                    text,
  codigo_empresa                      text,
  matricula                           text,
  cpf                                 text,
  email_usuario                       text,
  login                               text,
  tipo_usuario                        text,
  nome_completo                       text,
  data_admissao                       text,
  data_desligamento                   text,
  data_nascimento                     text,
  cod_gestor                          text,
  nivel                               text,
  multi_usuario                       text,
  codigo_unidade_funcional            text,
  nome_unidade_funcional              text,
  codigo_unidade_pai                  text,
  codigo_primeiro_gestor_uf           text,
  codigo_segundo_gestor_uf            text,
  atualiza_gestor_colaboradores       text,
  codigo_cargo                        text,
  nome_cargo                          text,
  nome_classificacao                  text,
  situacao_processamento              text,
  mensagem                            text,
  raw_data                            jsonb,
  synced_at                           timestamptz default now()
);

-- Lote de integrações
create table if not exists elofy_integration_batch (
  id                            uuid primary key default gen_random_uuid(),
  elofy_id                      text unique not null,
  codigo_grupo_economico        text,
  data_inicio                   text,
  data_fim                      text,
  qtd_registros_integrados      integer,
  situacao_lote                 text,
  raw_data                      jsonb,
  synced_at                     timestamptz default now()
);
-- Log de sincronizações
create table if not exists elofy_sync_logs (
  id              uuid primary key default gen_random_uuid(),
  entity          text not null,
  status          text not null check (status in ('success', 'error', 'running', 'token_expired')),
  records_synced  integer default 0,
  error_message   text,
  started_at      timestamptz default now(),
  finished_at     timestamptz
);

create index if not exists idx_sync_logs_entity on elofy_sync_logs(entity);
create index if not exists idx_sync_logs_started_at on elofy_sync_logs(started_at desc);
