-- Competências
create table if not exists elofy_competencies (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  competencia           text,
  categoria             text,
  descricao             text,
  ids_times             text,
  nomes_times           text,
  ids_cargos            text,
  nomes_cargos          text,
  esperado              text,
  o_que_queremos        text,
  o_que_nao_queremos    text,
  comportamentos        text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Configurações de revisão de ciclo
create table if not exists elofy_cycle_review_config (
  id                              uuid primary key default gen_random_uuid(),
  elofy_id                        text unique not null,
  id_empresa                      text,
  nome_empresa                    text,
  id_revisao                      text,
  nome_ciclo                      text,
  id_ciclo                        text,
  nome_revisao                    text,
  status_revisao                  text,
  liberacao_notas                 text,
  calibracao_notas                text,
  responder_avaliacoes            text,
  ano                             text,
  janela                          text,
  trimestre_inicio                text,
  trimestre_fim                   text,
  data_inicio_ciclo               text,
  data_fim_ciclo                  text,
  dias_faltando                   text,
  regua                           text,
  data_corte_elegibilidade        text,
  tipo_publico                    text,
  etapa                           text,
  nome_etapa                      text,
  autoavaliacao                   text,
  pares                           text,
  clientes_internos               text,
  gestor                          text,
  equipe                          text,
  permitir_comentarios            text,
  comentarios_obrigatorios        text,
  gestores_avaliados              text,
  selecao_pares_rh                text,
  visualizacao_rapida_objetivos   text,
  avaliar_okr                     text,
  avaliar_responsaveis_kr         text,
  avaliar_responsaveis_corresps   text,
  nao_avaliar_kr_estrategicos     text,
  avaliacao_por_entregas          text,
  avaliacao_responsaveis_init     text,
  raw_data                        jsonb,
  synced_at                       timestamptz default now()
);
