-- Avaliação detalhada (nível raiz)
create table if not exists elofy_cycle_review_detailed (
  id                          uuid primary key default gen_random_uuid(),
  elofy_id                    text unique not null,
  id_revisao_ciclo            text,
  ano                         integer,
  nome_ciclo                  text,
  id_empresa                  text,
  id_revisao_ciclos_avaliacoes text,
  id_avaliado                 text,
  matricula_avaliado          text,
  nome_avaliado               text,
  id_time_avaliado            text,
  nome_time_avaliado          text,
  tipo_cargo_avaliado         text,
  id_tipo_cargo_avaliado      text,
  id_cargo_avaliado           text,
  cargo_avaliado              text,
  id_gestor_avaliado          text,
  gestor_avaliado             text,
  media_final_avaliacao       text,
  label_nbox                  text,
  quadrante_nbox              text,
  tipo_avaliacao              text,
  id_avaliador                text,
  matricula_avaliador         text,
  avaliador                   text,
  id_time_avaliador           text,
  nome_time_avaliador         text,
  tipo_cargo_avaliador        text,
  id_cargo_avaliador          text,
  cargo_avaliador             text,
  raw_data                    jsonb,
  synced_at                   timestamptz default now()
);

-- Etapas da avaliação detalhada
create table if not exists elofy_cycle_review_steps (
  id                          uuid primary key default gen_random_uuid(),
  elofy_id                    text unique not null,
  cycle_review_detailed_id    text not null,
  etapa                       text,
  media_fase                  numeric,
  nome_etapa                  text,
  conceito_media_etapa        text,
  comentario_unico_fase       text,
  id_revisao_ciclo_fases      text,
  raw_data                    jsonb,
  synced_at                   timestamptz default now()
);

-- Itens avaliados dentro das etapas
create table if not exists elofy_cycle_review_items (
  id                                  uuid primary key default gen_random_uuid(),
  elofy_id                            text unique not null,
  step_id                             text not null,
  nota                                numeric,
  conceito                            text,
  comentario                          text,
  item_avaliado                       text,
  id_revisao_ciclo_avaliacoes_fase    text,
  raw_data                            jsonb,
  synced_at                           timestamptz default now()
);

-- Revisão de ciclo público (scores por colaborador)
create table if not exists elofy_cycle_review_public (
  id                          uuid primary key default gen_random_uuid(),
  elofy_id                    text unique not null,
  id_empresa                  text,
  id_revisao_score            text,
  id_revisao_ciclo            text,
  nome_revisao                text,
  id_usuario_avaliado         text,
  matricula_avaliado          text,
  nome_avaliado               text,
  status_avaliado             text,
  media_final                 text,
  fase                        text,
  media_fase                  text,
  media_fase_auto             text,
  media_fase_gestor           text,
  media_fase_pares            text,
  media_fase_equipe           text,
  media_fase_cliente          text,
  raw_data                    jsonb,
  synced_at                   timestamptz default now()
);

-- Notas por fase (Carreira)
create table if not exists elofy_cycle_review_note_step (
  id                              uuid primary key default gen_random_uuid(),
  elofy_id                        text unique not null,
  id_empresa                      text,
  id_revisao_score                text,
  id_revisao_ciclo                text,
  nome_revisao                    text,
  id_usuario_avaliado             text,
  nome_usuario                    text,
  status_avaliado                 text,
  id_gestor                       text,
  nome_gestor                     text,
  media_final_ciclo               text,
  conceito_final_ciclo            text,
  conceito_final_ciclo_calibrado  text,
  nine_box                        text,
  quadrante_nbox                  text,
  quadrante_nbox_calibrado        text,
  media_fase_competencia          text,
  conceito_fase_competencia       text,
  media_competencia_auto          text,
  conceito_competencia_auto       text,
  media_competencia_gestor        text,
  conceito_competencia_gestor     text,
  media_competencia_pares         text,
  conceito_competencia_par        text,
  media_competencia_time          text,
  conceito_competencia_time       text,
  media_competencias_clientes     text,
  conceito_competencia_clientes   text,
  media_resultados                text,
  conceito_resultados             text,
  media_resultados_auto           text,
  conceito_resultados_auto        text,
  media_resultados_gestor         text,
  conceito_resultados_gestor      text,
  media_resultados_pares          text,
  conceito_resultados_pares       text,
  media_resultados_time           text,
  conceito_resultados_time        text,
  media_resultados_clientes       text,
  conceito_resultados_clientes    text,
  media_valores                   text,
  conceito_valores                text,
  media_valores_auto              text,
  conceito_valores_auto           text,
  media_valores_gestor            text,
  conceito_valores_gestor         text,
  media_valores_pares             text,
  conceito_valores_pares          text,
  media_valores_time              text,
  conceito_valores_time           text,
  media_valores_clientes          text,
  conceito_valores_clientes       text,
  raw_data                        jsonb,
  synced_at                       timestamptz default now()
);

-- Médias fase competências
create table if not exists elofy_cycle_review_avg_competencies (
  id                              uuid primary key default gen_random_uuid(),
  elofy_id                        text unique not null,
  id_empresa                      text,
  id_revisao_score                text,
  id_revisao_ciclo                text,
  nome_revisao                    text,
  periodo                         text,
  id_usuario_avaliado             text,
  nome_usuario_avaliado           text,
  id_gestor                       text,
  nome_gestor                     text,
  conceito_final_ciclo            text,
  media_final_ciclo_calibrado     text,
  conceito_final_ciclo_calibrado  text,
  media_competencia               text,
  media_competencia_auto          text,
  media_competencia_gestor        text,
  media_competencia_pares         text,
  media_competencia_equipe        text,
  media_competencia_clientes      text,
  raw_data                        jsonb,
  synced_at                       timestamptz default now()
);

-- Médias fase resultados
create table if not exists elofy_cycle_review_avg_results (
  id                              uuid primary key default gen_random_uuid(),
  elofy_id                        text unique not null,
  id_empresa                      text,
  id_revisao_avaliacoes_fase      text,
  id_revisao_ciclo                text,
  nome_revisao                    text,
  id_usuario_avaliado             text,
  nome_usuario_avaliado           text,
  id_gestor                       text,
  nome_gestor                     text,
  conceito_final_ciclo            text,
  media_final_ciclo_calibrado     text,
  conceito_final_ciclo_calibrado  text,
  media_final_fase_resultados     text,
  item_avaliado                   text,
  media_item_avaliado             text,
  media_item_auto                 text,
  media_item_gestor               text,
  media_item_pares                text,
  media_item_equipe               text,
  media_item_clientes             text,
  media_final                     text,
  raw_data                        jsonb,
  synced_at                       timestamptz default now()
);

-- Ninebox
create table if not exists elofy_cycle_review_ninebox (
  id                              uuid primary key default gen_random_uuid(),
  elofy_id                        text unique not null,
  id_empresa                      text,
  id_revisao_score                text,
  id_revisao_ciclo                text,
  periodo                         text,
  nome_revisao                    text,
  data_inicio                     timestamptz,
  data_fim                        timestamptz,
  id_usuario_avaliado             text,
  nome_usuario_avaliado           text,
  status_avaliado                 text,
  id_gestor                       text,
  nome_gestor                     text,
  media_final_ciclo               text,
  conceito_final_ciclo            text,
  conceito_final_ciclo_calibrado  text,
  fase_eixo_x                     text,
  nota_eixo_x                     text,
  fase_eixo_y                     text,
  nota_eixo_y                     text,
  quadrante_nbox                  text,
  quadrante_nbox_calibrado        text,
  pessoa_chave                    text,
  talento                         text,
  singular                        text,
  reconhecimento                  text,
  raw_data                        jsonb,
  synced_at                       timestamptz default now()
);
