-- Períodos
create table if not exists elofy_periods (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  periodo               text,
  data_inicio           text,
  data_fim              text,
  situacao              text,
  escala_peso_obj       text,
  nome_padrao_objetivo  text,
  escala_peso_kr        text,
  periodicidade_kr      text,
  modulo                text,
  id_empresa            text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Períodos detalhados
create table if not exists elofy_periods_detailed (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  periodo                   text,
  data_inicial              date,
  data_final                date,
  escala_pesos_kr           text,
  escala_pesos_meta         text,
  possui_ciclo_competencias text,
  ciclos_com_competencias   text,
  amplitude_competencia     text,
  possui_ciclo_potencial    text,
  ciclos_com_potencial      text,
  amplitude_potencial       text,
  possui_ciclo_valores      text,
  ciclos_com_valores        text,
  amplitude_valores         text,
  possui_ciclo_resultados   text,
  ciclos_com_resultados     text,
  amplitude_resultados      text,
  possui_ciclo_feedback     text,
  ciclos_com_feedback       text,
  amplitude_feedback        text,
  possui_ciclos_nota_final  text,
  ciclos_nota_final         text,
  possui_ppr                text,
  possui_rv                 text,
  possui_calibragem         text,
  ciclos_com_calibragem     text,
  possui_nbox               text,
  ciclos_nbox               text,
  possui_pdi                text,
  possui_sucessao           text,
  possui_feedback           text,
  possui_one_one            text,
  quantidade_pdis           integer,
  quantidade_feedback       integer,
  quantidade_one_one        integer,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Ciclos
create table if not exists elofy_cycles (
  id          uuid primary key default gen_random_uuid(),
  elofy_id    text unique not null,
  ciclo       text,
  id_periodo  text,
  data_inicio text,
  data_fim    text,
  situacao    text,
  status      text,
  id_empresa  text,
  raw_data    jsonb,
  synced_at   timestamptz default now()
);

-- Direcionadores
create table if not exists elofy_drivers (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  id_periodo                text,
  nome_periodo              text,
  nome_direcionador         text,
  progresso                 text,
  descricao                 text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  matricula_gestor          text,
  status                    text,
  atrela_metas              text,
  tipo_direcionador         text,
  corresponsaveis           jsonb,
  tags                      jsonb,
  itens_vinculados          jsonb,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Objetivos
create table if not exists elofy_objectives (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  id_periodo                text,
  periodo                   text,
  id_ciclo                  text,
  ciclo                     text,
  id_direcionador           text,
  direcionador              text,
  id_objetivo_pai           text,
  objetivo_pai              text,
  objetivo                  text,
  objetivo_estrategico      text,
  descricao                 text,
  tipo                      text,
  id_responsavel            text,
  responsavel               text,
  id_corresponsavel         text,
  corresponsavel            text,
  time                      text,
  workflow                  text,
  tags                      text,
  peso                      text,
  progresso                 text,
  sentimento                text,
  status                    text,
  ativo                     text,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Resultados chave (Key Results)
create table if not exists elofy_key_results (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_objetivo           text,
  resultado_chave       text,
  descricao             text,
  workflow              text,
  id_responsavel        text,
  responsavel           text,
  id_corresponsavel     text,
  corresponsavel        text,
  peso                  text,
  unidade_medida        text,
  meta                  text,
  ponto_partida         text,
  direcao               text,
  manutencao            text,
  medicao_atual         text,
  data_medicao_atual    text,
  progresso             text,
  periodicidade         text,
  checkins_pendentes    text,
  sentimento            text,
  status                text,
  tipo_informacao       text,
  tipo_score            text,
  formula_calculo       text,
  tags                  text,
  modulo                text,
  ativo                 text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- OKRs V2
create table if not exists elofy_okrs_v2 (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  nome_objetivo             text,
  ativo                     text,
  workflow                  text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  matricula_gestor          text,
  peso                      text,
  progresso                 text,
  id_periodo                text,
  periodo                   text,
  periodo_ciclos            jsonb,
  corresponsaveis           jsonb,
  resultados_chave          jsonb,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Contrato de metas V2
create table if not exists elofy_goals_contract_v2 (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  nome_objetivo             text,
  ativo                     text,
  workflow                  text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  matricula_gestor          text,
  peso                      text,
  progresso                 text,
  id_periodo                text,
  periodo                   text,
  periodo_ciclos            jsonb,
  metas                     jsonb,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Base de indicadores
create table if not exists elofy_base_indicators (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_empresa            text,
  nome_empresa          text,
  nome_indicador        text,
  descricao             text,
  ativo                 text,
  dimensao              text,
  origem                text,
  peso                  text,
  tipo_informacao       text,
  forma_calculo         text,
  tipo_score            text,
  id_periodo            text,
  nome_periodo          text,
  casas_decimais        integer,
  ponto_partida         text,
  periodicidade         text,
  manutencao            text,
  meta                  text,
  score                 text,
  minimo                text,
  maximo                text,
  maximo2               text,
  meta_jan              text,
  checkin_jan           text,
  meta_fev              text,
  checkin_fev           text,
  meta_mar              text,
  checkin_mar           text,
  meta_abr              text,
  checkin_abr           text,
  meta_maio             text,
  checkin_maio          text,
  meta_jun              text,
  checkin_jun           text,
  meta_jul              text,
  checkin_jul           text,
  meta_ago              text,
  checkin_ago           text,
  meta_set              text,
  checkin_set           text,
  meta_out              text,
  checkin_out           text,
  meta_nov              text,
  checkin_nov           text,
  meta_dez              text,
  checkin_dez           text,
  meta_anual            text,
  checkin_anual         text,
  metas_vinculadas      jsonb,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);
