-- PDI
create table if not exists elofy_pdi (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_empresa            text,
  id_responsavel        text,
  matricula             text,
  responsavel           text,
  titulo_pdi            text,
  cargo_responsavel     text,
  time_responsavel      text,
  cargos_vinculados     text,
  competencias_vinculadas text,
  prazo                 text,
  status_pdi            text,
  progresso_pdi         text,
  situacao_pdi          text,
  id_iniciativa         text,
  iniciativa            text,
  tipo_iniciativa       text,
  prazo_iniciativa      text,
  status_iniciativa_label text,
  progresso_iniciativa  text,
  status_iniciativa     text,
  data_conclusao        text,
  data_criacao_iniciativa text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Iniciativas
create table if not exists elofy_initiatives (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  iniciativa                text,
  descricao                 text,
  nro_sub_iniciativas       integer,
  id_iniciativa_pai         text,
  nome_iniciativa_pai       text,
  status_iniciativa         text,
  data_inicio               date,
  data_final                text,
  situacao_iniciativa       text,
  progresso_iniciativa      integer,
  data_conclusao            date,
  disponivel_avaliacao      text,
  origem                    text,
  tags                      text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  corresponsaveis           text,
  id_resultado_chave        text,
  resultado_chave           text,
  progresso_resultado_chave integer,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Iniciativas PDI
create table if not exists elofy_initiatives_pdi (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  iniciativa                text,
  descricao                 text,
  status_iniciativa         text,
  data_inicio               text,
  data_final                text,
  situacao_iniciativa       text,
  data_conclusao            text,
  progresso_iniciativa      integer,
  disponivel_avaliacao      text,
  origem                    text,
  tags                      text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  data_criacao              text,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Iniciativas 1-1
create table if not exists elofy_initiatives_one_one (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_empresa              text,
  iniciativa                text,
  status_iniciativa         text,
  data_inicio               text,
  data_final                text,
  situacao_iniciativa       text,
  data_conclusao            text,
  progresso_iniciativa      integer,
  disponivel_avaliacao      text,
  origem                    text,
  id_responsavel            text,
  nome_responsavel          text,
  matricula_responsavel     text,
  id_cargo                  text,
  cargo                     text,
  nivel_responsabilidade    text,
  id_time_responsavel       text,
  nome_time_responsavel     text,
  id_gestor_responsavel     text,
  nome_gestor_responsavel   text,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);
