-- Pesquisas (relatório geral sem respostas)
create table if not exists elofy_surveys (
  id                        uuid primary key default gen_random_uuid(),
  elofy_id                  text unique not null,
  id_empresa                text,
  nome_pesquisa             text,
  id_tipo_pesquisa          text,
  tipo_pesquisa             text,
  id_questionario           text,
  questionario              text,
  data_inicio               text,
  data_fim                  text,
  situacao                  text,
  pesquisa_anonima          text,
  numero_pendencias         text,
  numero_respondentes       text,
  adesao                    text,
  status_pesquisa           text,
  raw_data                  jsonb,
  synced_at                 timestamptz default now()
);

-- Pesquisas de desligamento
create table if not exists elofy_survey_dismiss (
  id                          uuid primary key default gen_random_uuid(),
  elofy_id                    text unique not null,
  id_empresa                  text,
  id_pesquisa                 text,
  nome_pesquisa               text,
  id_publico_pesquisa         text,
  id_usuario_desligado        text,
  matricula_usuario_desligado text,
  usuario_desligado           text,
  id_cargo_desligado          text,
  cargo_desligado             text,
  id_time_desligado           text,
  time_desligado              text,
  id_gestor_desligado         text,
  matricula_gestor_desligado  text,
  nome_gestor_desligado       text,
  data_desligamento           text,
  id_tipo_desligamento        text,
  tipo_desligamento           text,
  id_usuario_respondente      text,
  matricula_respondente       text,
  usuario_respondente         text,
  id_cargo_respondente        text,
  nome_cargo_respondente      text,
  id_time_respondente         text,
  time_respondente            text,
  modo_envio_pesquisa         text,
  id_pergunta                 text,
  id_resposta                 text,
  pergunta                    text,
  justificativa               text,
  resposta                    text,
  status_pesquisa             text,
  data_resposta               text,
  id_categoria_pergunta       text,
  nome_categoria_pergunta     text,
  status_pesquisa_ativa       text,
  raw_data                    jsonb,
  synced_at                   timestamptz default now()
);

-- Pesquisas Pulse
create table if not exists elofy_survey_pulse (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_empresa            text,
  id_pesquisa           text,
  nome_pesquisa         text,
  situacao_pesquisa     text,
  data_pulso            text,
  data_resposta         text,
  id_usuario            text,
  usuario               text,
  id_time               text,
  time                  text,
  id_gestor             text,
  gestor                text,
  id_categoria_pergunta text,
  categoria_pergunta    text,
  id_pergunta           text,
  pergunta              text,
  score_resposta        text,
  resposta              text,
  justificativa         text,
  id_resposta           text,
  status_pesquisa       text,
  id_publico_pesquisa   text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Pesquisas Padrão e Enquetes
create table if not exists elofy_survey_standard (
  id                    uuid primary key default gen_random_uuid(),
  elofy_id              text unique not null,
  id_empresa            text,
  id_pesquisa           text,
  nome_pesquisa         text,
  situacao_pesquisa     text,
  data_envio_pesquisa   text,
  id_usuario            text,
  usuario               text,
  id_cargo              text,
  cargo                 text,
  id_time               text,
  time                  text,
  id_gestor             text,
  nome_gestor           text,
  status_resposta       text,
  data_resposta         text,
  id_categoria_pergunta text,
  categoria_pergunta    text,
  id_tipo_pergunta      text,
  tipo_pergunta         text,
  id_pergunta           text,
  pergunta              text,
  resposta              text,
  justificativa         text,
  status_pesquisa       text,
  id_resposta           text,
  id_publico_pesquisa   text,
  raw_data              jsonb,
  synced_at             timestamptz default now()
);

-- Pesquisas Temporais
create table if not exists elofy_survey_temporal (
  id                          uuid primary key default gen_random_uuid(),
  elofy_id                    text unique not null,
  id_empresa                  text,
  id_pesquisa                 text,
  nome_pesquisa               text,
  situacao_pesquisa           text,
  data_envio_pesquisa         date,
  id_tipo_respondente         text,
  tipo_respondente            text,
  id_usuario_respondente      text,
  usuario_respondente         text,
  id_cargo_respondente        text,
  cargo_respondente           text,
  id_time_respondente         text,
  time_respondente            text,
  id_usuario_avaliado         text,
  usuario_avaliado            text,
  id_cargo_avaliado           text,
  cargo_avaliado              text,
  id_time_avaliado            text,
  time_avaliado               text,
  data_admissao_avaliado      text,
  status_resposta             text,
  data_resposta               text,
  id_categoria_pergunta       text,
  categoria_pergunta          text,
  id_tipo_pergunta            text,
  tipo_pergunta               text,
  id_pergunta                 text,
  pergunta                    text,
  resposta                    text,
  justificativa               text,
  status_pesquisa             text,
  id_resposta                 text,
  id_publico_pesquisa         text,
  raw_data                    jsonb,
  synced_at                   timestamptz default now()
);
